#!/usr/bin/env python

import sys
import uuid
sys.path.append('lib')

from charms.rados_bench import Rados
from charmhelpers.core.hookenv import (
    action_set,
    action_get,
)

r = Rados()
pool = str(uuid.uuid4())
r.create_pool(pool)

results = r.bench(pool,
                  'write',
                  action_get('seconds'),
                  action_get('op-size'),
                  action_get('concurrent-operations'))

r.delete_pool(pool)

action_set('meta.raw', results)
