#!/usr/bin/env python

import os
import sys
import uuid
sys.path.append('lib')

from charms.rados_bench import Rados
from charmhelpers.core.hookenv import (
    action_set,
    action_get,
)

from charmbenchmark import Benchmark

r = Rados()
pool = str(os.environ.get('JUJU_ACTION_ID', uuid.uuid4()))
r.create_pool(pool)

Benchmark.start()
results = r.bench(pool,
                  'write',
                  action_get('seconds'),
                  action_get('op-size'),
                  action_get('concurrent-operations'))
Benchmark.finish()
r.delete_pool(pool)

action_set(results)
